### ISSUE TITLE
Better PEP-8 Compliance

### ISSUE THREAD

**Issue by Bugzey** [Curts0/PyTabular#39]
Skimming through the code, I see that we are violating quite a lot of standard Python conventions both in the object names, project structure, and imports. Considering that the project is considered in early alpha, would it be OK to take steps to make backwards-incompatible changes at this point in time and apply as many conventions as possible?

Most notably, I'd like to focus on the following:

- Object naming:
  - snake_case: `function_name`, `method_name`, `global_variable_name`
  - CapitalCase: `ClassName`, `ExceptionName`
  - SCREAMING_SNAKE_CASE: `GLOBAL_CONSTANT`
- Line length - while PEP-8 recommends 72 characters, I can recommend 100 from my personal experience. This goes doubly so for docstrings
- Standardized docstring format - you seem to be using the Google Python guide on this matter, although line lengths and indentation are off. This could be fixed easily [Reference](https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings)
- Using only absolute imports from the project:
  - `from pytabular.sub_module import whatever` (You seem to have fixed that recently?)
- Using a `tests` folder (plural)

Implementing the above would probably also remove some flake8 exceptions the project has identified.

**Comment by Curts0** [comment]
Agreed labelling as bug. I made a first pass at getting closer to Pep8. I run [black](https://pypi.org/project/black/) locally and have flake8 running with exceptions (that I didn't want to deal with at the time) on pull requests already. Will keep this open till I myself or others can clean this up.

**Comment by Daandamhuis** [comment]
Do you want to spend sometime refactoring this, to make sure that it's correct for the future?

**Comment by Curts0** [comment]
Here is where we are at so far.

- A GitHub action will run a flake8 test for PEP8 Compliance before merging to the main branch. But I'm ignoring a few rules: [.flake8 file](https://github.com/Curts0/PyTabular/blob/744273eb391f7ee4a575ff5c515ad5beb426e577/.flake8) because I didn't have the time to make it compatible. 
- Some rules are ignored on purpose, because of the compatibility with Black Styling and Flake8: https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
- And W503 issues are because of my docstrings. I'm using [mkgendocs](https://pypi.org/project/mkgendocs/) to help create this: [documentation](https://curts0.github.io/PyTabular/). We would need to look into how we can reduce the line length in docstrings, but maintain the conversion to the PyTabular documentation. Open to a better way to get documentation from docstrings, but just using that for now.

**Comment by Curts0** [comment]
- https://github.com/PyCQA/pep8-naming
- Use pep8-naming in tests to clean up naming conventions
- Will be a ton of breaking changes, will need to scope that out

**Comment by Curts0** [comment]
- Complete rework of naming and docstrings.
- Set line limit to 100.
- Removed all flake8 exceptions except for E203 for compatibility with black styling.
- Add pep8-naming and flake8-docstrings to flake8 test in github actions to maintain compliance going forward.
- [pep8-naming](https://github.com/PyCQA/pep8-naming)
- [flake8-docstrings](https://github.com/pycqa/flake8-docstrings)
