### ISSUE TITLE
Refresh the Model 

### ISSUE THREAD

**Issue by Daandamhuis** [Curts0/PyTabular#91]
Hi, 

Is there a way to first process Data Only and the Calculate?

```python 
import pytabular
model = pytabular.Tabular(CONNECTION_STR)
tables = model.Tables
if len(tables) > 0:
    tables.refresh(RefreshType.DataOnly)

model.refresh(RefreshType.Calculate)

```

**Comment by Curts0** [comment]
Hey @Daandamhuis not right now but would be an easy addition. I can probably get to it this weekend. Would be a good addition. Unless you already started with this? Sorry for the very delayed reply!

Can have a keyword arg that defaults to full but let's any of the refresh types get passed

**Comment by Curts0** [comment]
@Daandamhuis I lied lol. Turns out you can do it and I didn't know I built it that way.

```python
import pytabular
from pytabular.refresh import RefreshType
model = pyatbular.Tabular(CONNECTION_STR)
if len(tables) > 0:
    tables.refresh(refresh_type=RefreshType.DataOnly)

model.refresh(refresh_type=RefreshType.Calculate)
```

I import [RefreshType](https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.refreshtype?view=analysisservices-dotnet) in the refresh file.

The main `PyRefresh` class has the parameter `refresh_type`. So just pass the RefreshType you want in your refresh and you should be good to do.

**Comment by Daandamhuis** [comment]
Ahh that's cool! I'll see if I can get it working 😀
